import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from transformers import AutoModelForSequenceClassification
from accelerate import Accelerator
from wandb import WandbCallback
from model_architecture import VisualCoTModel
from data_loader import VisualCoTDataset
from typing import Dict, List, Tuple
import logging
from logging.handlers import RotatingFileHandler
import os
import json
from datetime import datetime
from torch.utils.data import Dataset
from torch.utils.data.dataloader import default_collate
from torch.nn.utils.rnn import pad_sequence
from torch.nn import functional as F
from einops import rearrange
from accelerate import Accelerator
from accelerate.utils import set_seed
from accelerate.logging import get_logger
from accelerate.utils import save_pretrained
from accelerate.utils import load_pretrained
from accelerate.utils import get_state_dict
from accelerate.utils import set_state_dict
from accelerate.utils import get_device
from accelerate.utils import move_to_device
from accelerate.utils import get_model_device
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import get_model_class
from accelerate.utils import get_model_name
from accelerate.utils import get_model_config
from accelerate.utils import get_model_state_dict
from accelerate.utils import get_model_device_map
from accelerate.utils import get_model_data_type
from accelerate.utils import get_model_precision
from accelerate.utils import get_model_dtype
from accelerate.utils import